# Liquid Neural Network (LTC based)

## Scratch Implementation
- LTCCell
- RNNCell
- LSTMCell
- Full Each cell based NN

### LTCCell

In [1]:
def sigmoid(x):
    e = 2.73
    return 1/(1+e^(-x))

In [ ]:
gate = sigmoid(Wx + b)

In [ ]:
tau = 0.23   # hyperparamter
tsys = 1/((1/tau) + gate)

In [3]:
def forward(hidden_state_x, input_I, dt):
    num = hidden_state_x + dt * gate * A
    den = 1 + dt * ((1/tau) + gate)

    new_hidden_state = num / den

In [37]:
import torch
import torch.nn as nn
import torch.optim as optim

In [38]:
class LTCCell(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LTCCell, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        # parameters
        # self.W = torch.parameters(shape)
        # self.b = torch.parameters(shape)
        self.A = nn.Parameter(torch.zeros(hidden_size))
        self.tau = nn.Parameter(torch.ones(hidden_size))

        self.f = nn.Linear(input_size + hidden_size, hidden_size)


    def forward(self, I, xt, dt=1):
        # horizontal stack: batch_size X (input_size + hidden_size)
        input_with_hidden = torch.cat([I, xt], dim=1)
        self.gate = torch.sigmoid(self.f(input_with_hidden))
        num = xt + dt * self.gate * self.A
        den = 1 + dt * ((1/self.tau) + self.gate)

        updated_xt = num / den
        return updated_xt


In [48]:
x = torch.ones(1, 5)
h = torch.ones(1, 10)

print(f"X = {x}")
print(f"Hidden state h = {h}")

X = tensor([[1., 1., 1., 1., 1.]])
Hidden state h = tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [49]:
cell = LTCCell(5, 10)
cell

LTCCell(
  (f): Linear(in_features=15, out_features=10, bias=True)
)

In [50]:
cell(x, h) # input comes every 1 second

tensor([[0.4084, 0.4143, 0.4354, 0.4131, 0.4368, 0.4019, 0.4103, 0.3958, 0.3959,
         0.4038]], grad_fn=<DivBackward0>)

In [51]:
# due to some sensor issue or some lag, there's a delay of 5 second
cell(x, h, 5)

tensor([[0.1213, 0.1239, 0.1336, 0.1234, 0.1343, 0.1185, 0.1221, 0.1158, 0.1159,
         0.1193]], grad_fn=<DivBackward0>)

In [52]:
# due to some sensor issue or some lag, there's a delay of 2 second
cell(x, h, 2)

tensor([[0.2566, 0.2613, 0.2783, 0.2603, 0.2795, 0.2515, 0.2581, 0.2467, 0.2468,
         0.2529]], grad_fn=<DivBackward0>)

### RNN from scratch

In [44]:
class RNNCell(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(RNNCell, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2h = nn.Linear(hidden_size, hidden_size)

    def forward(self, input_data, h_state):
        h_raw = self.i2h(input_data) + self.h2h(h_state)
        updated_hidden_state = torch.tanh(h_raw)
        return updated_hidden_state

In [53]:
x_rnn = torch.ones(1, 5)
h_rnn = torch.ones(1, 10)

print(f"X = {x_rnn}")
print(f"Hidden state h = {h_rnn}")

X = tensor([[1., 1., 1., 1., 1.]])
Hidden state h = tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [54]:
rnncell = RNNCell(5, 10)
rnncell

RNNCell(
  (i2h): Linear(in_features=5, out_features=10, bias=True)
  (h2h): Linear(in_features=10, out_features=10, bias=True)
)

In [55]:
rnncell(x_rnn, h_rnn)

tensor([[-0.3778,  0.1221, -0.4948, -0.7518, -0.1676, -0.0546,  0.5180, -0.3438,
         -0.5297, -0.3968]], grad_fn=<TanhBackward0>)

### LSTM from Scratch

In [62]:
class LSTMCell(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LSTMCell, self).__init__()
        self.hidden_size = hidden_size

        self.gates = nn.Linear(input_size + hidden_size, hidden_size * 4)

    def forward(self, input_data, states):
        h_state, cell_state = states

        combined = torch.cat([input_data, h_state], dim=1)
        gates_output = self.gates(combined)
        # to separate out all 4 matrices
        forget, input_, input_tanh, output = torch.chunk(gates_output, 4, dim=1)

        forget_gate = cell_state * torch.sigmoid(forget)

        input_gate = torch.sigmoid(input_) * torch.tanh(input_tanh)
        updated_cell_state = input_gate + forget_gate

        output_gate = torch.sigmoid(output) * torch.tanh(updated_cell_state)

        updated_h_state = output_gate

        return updated_h_state, updated_cell_state


In [63]:
x_lstm = torch.ones(1, 5)
c_lstm = torch.ones(1, 10)
h_lstm = torch.ones(1, 10)

print(f"X = {x_lstm}")
print(f"Cell state c = {c_lstm}")
print(f"Hidden state h = {h_lstm}")

X = tensor([[1., 1., 1., 1., 1.]])
Cell state c = tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
Hidden state h = tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [64]:
lstm_cell = LSTMCell(5, 10)
lstm_cell

LSTMCell(
  (gates): Linear(in_features=15, out_features=40, bias=True)
)

In [65]:
lstm_cell(x_lstm, (h_lstm, c_lstm))

(tensor([[0.2671, 0.1710, 0.2829, 0.2570, 0.1114, 0.0265, 0.3113, 0.1259, 0.1069,
          0.1121]], grad_fn=<MulBackward0>),
 tensor([[0.5041, 0.4971, 0.6520, 0.4007, 0.2938, 0.0848, 0.5177, 0.3900, 0.2658,
          0.2460]], grad_fn=<AddBackward0>))

## Scratch Implementation (Pytorch)

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
class LTCCell(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LTCCell, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size

        # Gate mechanism - func f: Input I(t), hidden_state x(t)
        self.f = nn.Linear(in_features=input_size + hidden_size, out_features=hidden_size)

        # parameters
        # Tau (Base time-constant)
        # A (Bias)
        self.tau = nn.Parameter(torch.ones(hidden_size))
        self.A = nn.Parameter(torch.ones(hidden_size))

    def forward(self, input_data, h_state, *, dt=1.0):
        combined = torch.cat([input_data, h_state], dim=1)

        self.gate = torch.sigmoid(self.f(combined))

        # Closed-form update (implicit step)
        # numerator pushes X towards A based upon input strength
        num = h_state + dt * self.gate * self.A
        # denominator stabilities the X & prevents explosion.
        den = 1 + dt * (1/self.tau + self.gate)
        update_state = num / den

        return update_state
        
        

### checks

In [3]:
ltc_model = LTCCell(input_size=5, hidden_size=10)
x = torch.randn(3, 5)
h = torch.zeros(3, 10)
print(f"Input shape: {x.shape}")
print(f"Input sample: {x[: :2]}")

h_new = ltc_model(x, h, dt=0.5)
print(f"Output shape: {h_new.shape}")
print(f"Output sample: {h_new[:, :2]}")

Input shape: torch.Size([3, 5])
Input sample: tensor([[ 0.4173,  1.4876,  1.1073,  0.7345, -1.2982],
        [-0.3537, -0.4150,  0.6590, -0.3856,  0.2908]])
Output shape: torch.Size([3, 10])
Output sample: tensor([[0.1582, 0.1305],
        [0.1689, 0.1809],
        [0.1571, 0.1647]], grad_fn=<SliceBackward0>)


### LTCModel

In [ ]:
class LTCModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(LTCModel, self).__init__()
        self.ltc_cell = LTCCell(input_size, hidden_size)
        self.hidden_size = hidden_size
        self.output_size = output_size

        # layer to map Brain State to Prediction state
        self.readout = nn.Linear(hidden_size, output_size)

    def forward(self, x, times):
        """
        X: input
        times: dt for each step
        """
        batch_size, seq_len, _ = x.shape

        h_state = torch.zeros(batch_size, self.ltc_cell.hidden_size, device=x.device)

        time_states = []
        for t in range(seq_len):
            input_step = x[:, t, :]
            # reshape to (batch_size, 1)
            dt_step = times[:, t].unsqueeze(-1)
            # update hidden state
            h_state = self.ltc_cell(input_step, h_state, dt=dt_step)
            time_states.append(h_state)

        # stacking: (Batch, seq_len, hidden state)
        rnn_outputs = torch.stack(time_states, dim=1)
        preds = self.readout(rnn_outputs)
        return preds